name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semantic version to release'
        required: true
        default: '0.1.0'

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore & Pack
        run: |
          dotnet tool restore
          bash build.sh Pack --release-version ${{ github.event.inputs.version }}
