name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semantic version to release'
        required: true
        default: '0.1.0'

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Decode SNK
        run: |
          echo "${{ secrets.DUMMYLIB_SNK }}" | base64 --decode > DummyLib.snk

      - name: Create tag version
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "v${{ github.event.inputs.version }}" -m "Release v${{ github.event.inputs.version }}"

      - name: Generate CHANGELOG.md
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ github.event.inputs.version }}

      - name: Cat CHANGELOG.md
        run: |
          cat CHANGELOG.md

#      - name: Commit CHANGELOG.md
#        uses: EndBug/add-and-commit@v9
#        with:
#          author_name: 'github-actions[bot]'
#          author_email: 'github-actions[bot]@users.noreply.github.com'
#          message: "docs: update CHANGELOG for v${{ github.event.inputs.version }} [skip ci]"
#          add: 'CHANGELOG.md'

      - name: Restore & Pack
        run: |
          bash build.sh Pack --release-version ${{ github.event.inputs.version }}

      - name: Push tag version
        run: |
          git push origin "v${{ github.event.inputs.version }}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: v${{ github.event.inputs.version }}
          body: ${{ steps.changelog.outputs.changes }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
